apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  namespace: dev
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  type: LoadBalancer    
  selector:
    app: frontend
